
import { cn } from '@/lib/utils'
import './globals.css'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Script from 'next/script'
import Navbar from '@/components/Navbar'
import Providers from '@/components/Providers'
// import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Quizmify ',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Script
        type="text/javascript"
        src="../node_modules/tw-elements/dist/js/tw-elements.umd.min.js"></Script>
        {/* <Head>
        <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'/>
        </Head> */}
      <body className={cn(inter.className, "antialiased min-h-screen")}>        <Providers>
          <Navbar />
          <div className='pt-16'>
          {children}
          </div>
        </Providers>
     
      </body>
    </html>
  )
}
